enableTelemetry: false

enableTransparentWorkspaces: false

nodeLinker: node-modules

npmPublishRegistry: 'https://registry.npmjs.org'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.3.1/bundles/@yarnpkg/plugin-after-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-tsconfig-references.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-tsconfig-references.js'
  - path: .yarn/plugins/@yarnpkg/plugin-changed.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-changed.js'
  - path: .yarn/plugins/@yarnpkg/plugin-publishconfig.cjs
    spec: 'https://raw.githubusercontent.com/alizeait/yarn-plugin-publishconfig/v1.0/bundles/@yarnpkg/plugin-publishconfig.js'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.6.1.cjs
