compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: false

enableMirror: true

enableTelemetry: false

enableTransparentWorkspaces: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?

nodeLinker: node-modules

npmPublishRegistry: 'https://registry.npmjs.org'

plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.0.0.cjs
