#!/usr/bin/bash

echo "Checking if Vercel deployment should be skipped..."

# If VERCEL_GIT_COMMIT_REF env var starts with "renovate/", then exit with 0 to
# block the Vercel deployment.

if [[ "${VERCEL_GIT_COMMIT_REF}" == "renovate"/* ]]; then
  echo "Renovate branch detected! Skipping deployment!"
  exit 0
fi

# If the commit message contains "[skip ci]" (e.g. release commit generated by
# semantic release), then exit with 0 to block the Vercel deployment.

if [[ "${VERCEL_GIT_COMMIT_MESSAGE}" == *"[skip ci]"* ]]; then
  echo "Commit message contains \"[skip ci]\"! Skipping deployment!"
  exit 0
fi

# Otherwise exit with 1 to carry on with the deployment.

echo "Continuing with deployment!"

exit 1
